### PR TITLE
boat model created with validation - foreign key to be implemented

### PR DESCRIPTION
**Pull request by Mithrandir90**
Boat model created, with validations. Some have to be implemented as location and category.

### CODE REVIEW

**Comment by arnoldboy123** [comment]
It looks like your branch has some conflict with another branch which makes your branch not possible to be merged. Can you please resolve conflict

**Comment by AJboxell** [comment]
conflicts sorted out

**Comment by arnoldboy123** [comment]
Looks all good to me at a glance :)
Thanks Giuseppe!

**Comment by Mithrandir90** [comment]
Guys there are few changes due the seaplane, I had a look again and there was two file in test folder where I changed boat to seaplane manually. I will have a look again later on tonight, let's merge it tomorrow morning

**Comment by AJboxell** [comment]
one minor question from me - I forget exactly how we said we'd do availability and dates, but do we need that availability attribute for the seaplanes? Otherwise looks good!

**Comment by arnoldboy123** [comment]
That's a good point, I remember we're using client side authentication to check whether there are any availability, we could check with TA later

**Comment by arnoldboy123** [comment]
Availability is still there, we might have to come back to it later. Happy to merge for now.

**Pull request merged**
